services:
  # This is the name of your service on Render
  - type: web
    name: groveryworld-1
    runtime: python
    # This tells Render to look inside the 'backend' folder
    rootDir: backend
    # This command installs your Python packages
    buildCommand: pip install -r requirements.txt
    # This command starts your Flask app
    startCommand: gunicorn app:app
    # This tells Render your app is healthy
    healthCheckPath: /health